# Generated by Django 4.2 on 2023-06-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"verbose_name": "Booking", "verbose_name_plural": "Booking"},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={
                "ordering": ["id"],
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="resident",
            field=models.CharField(default=1, max_length=255, verbose_name="Resident"),
            preserve_default=False,
        ),
    ]
