# Generated by Django 4.2 on 2023-06-25 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_alter_room_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="end_time",
            new_name="end",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="start_time",
            new_name="start",
        ),
    ]
